# Generated by Django 3.1.3 on 2020-11-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_prescription', to='prescribe_app.patientinformation', verbose_name='Patient'),
        ),
    ]
