# Generated by Django 3.1.3 on 2020-12-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe_app', '0002_auto_20201115_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
