# Generated by Django 3.1.3 on 2020-12-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe_app', '0004_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_notes', to='prescribe_app.patientinformation'),
        ),
    ]
