# Generated by Django 3.1.3 on 2020-12-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescribe_app', '0005_auto_20201222_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
